### ISSUE TITLE
Fails Test 3 in TestStackMap.java

### ISSUE THREAD

**Issue by abalteanu** [abalteanu/pathfinderAssignment#1]
FIRST COMMIT ERRORS: DLStack.java without testing
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "DoubleLinkedNode.getElement()" because "this.top" is null
	at DLStack.peek(DLStack.java:118)
	at TestStackMap.main(TestStackMap.java:48)

**Comment by abalteanu** [comment]
forgot to include throw statement

**Comment by abalteanu** [comment]
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "DoubleLinkedNode.getElement()" because "curr" is null
	at DLStack.pop(DLStack.java:92)
	at TestStackMap.main(TestStackMap.java:54)

**Comment by abalteanu** [comment]
issue resolved, in public T pop(int k), had to change k to k-1 in for loop:
			for(int i = 0; i<k-1; i++) {
				// iterating through the list until the node to remove, starting from top and going to the previous node for the length
				curr = curr.getPrevious();
			}

all tests passed!
